language: python
sudo: required
dist: trusty

python:
  - "3.5.2"
  - "3.5"

install:
  - pip3 install codecov pytest pytest-cov
  - pip3 install -r requirements.txt
  - ./utils/scripts/jumpscale_install.sh
  - pip3 install -e .

script:
  - ./tests/prepare_env.sh
  - make test

after_success:
- codecov