[startup.openport]
name = "nft.open_port"
after = ["net"]

[startup.openport.args]
port = 6600

[startup.zrobot]
name = "corex.create-sync"
tags = ["zrobot"] #container tags
protected = true #set protected to true to respawn the container if it crashed
after = ["net", "openport"]

[startup.zrobot.args]
root = "https://hub.gig.tech/gig-autobuilder/zero-os-0-robot-autobuild.flist"
name = "zrobot"
privileged = false # or true depends on your need
host_network = false
# all other container create arguments are supported
#mounts = ? # probably need something from /var/cache for persistence
port = {6600=6600}
nics = [{type="default"}]
env = {LC_ALL="C.UTF-8", LANG="C.UTF-8"}
organization = "{organization}"

