[startup."zrobot-port"]
name = "nft.open_port"
after = ["net"]

[startup."zrobot-port".args]
port = 6600

[startup."zrobot-vol"]
name = "bash"
running_delay = -1

[startup."zrobot-vol".args]
script = """
set -e

ROOT=/var/cache

btrfs subvol create ${ROOT}/zrobot || true

for dir in ssh data config jsconfig; do
    mkdir -p ${ROOT}/zrobot/${dir}
done
"""

[startup.zrobot]
name = "corex.create-sync"
tags = ["zrobot"] #container tags
protected = true #set protected to true to respawn the container if it crashed
after = ["zrobot-port", "zrobot-vol"]

[startup.zrobot.args]
root = "https://hub.gig.tech/gig-autobuilder/zero-os-0-robot-autobuild.flist"
name = "zrobot"
privileged = false # or true depends on your need
host_network = false
# all other container create arguments are supported
#mounts = ? # probably need something from /var/cache for persistence
port = {6600=6600}
nics = [{type="default"}]
env = {LC_ALL="C.UTF-8", LANG="C.UTF-8"}
organization = "{organization}"

[startup.zrobot.args.mount]
"/var/cache/zrobot/ssh" = "/root/.ssh"
"/var/cache/zrobot/data" = "/opt/code/zrobot/zrobot_data"
"/var/cache/zrobot/config" = "/opt/code/zrobot/config"
"/var/cache/zrobot/jsconfig" = "/js9host/cfg"
"/var/run/redis.sock" = "/tmp/redis.sock"