[startup.zrobot]
name = "bash"
protected = true #set protected to true to respawn the container if it crashed


[startup.zrobot.args]
script = """
# workaround for https://github.com/zero-os/0-robot/issues/193
touch /lib/x86_64-linux-gnu/libtinfo.so.5.9

exec python3 /.startup.py
"""
