[startup.zrobot]
name = "bash"
protected = true #set protected to true to respawn the container if it crashed


[startup.zrobot.args]
script = """
export LC_ALL=C.UTF-8
export LANG=C.UTF-8
export HOME=/root


exec python3 /.startup.py
"""
